Repository AY2425S2-CS2103T-F14-4/tp, pull requests merged in 2025-04, with the labels that each got.

#114 docs: Update README.md and index.md
  README.md
  docs/images/Ui1.png
  docs/index.md
Labels: priority.High

#131 fix: Edit DeleteByCommand to handle person linked to event being deleted
  src/main/java/trackup/logic/commands/DeleteByCommand.java
  src/test/java/trackup/logic/commands/DeleteByCommandTest.java
Labels: priority.Medium, severity.Medium, alpha-bug

#137 fix: Edit SearchCommand to display suitable message for no matches
  src/main/java/trackup/logic/commands/SearchCommand.java
  src/test/java/trackup/logic/commands/SearchCommandTest.java
Labels: priority.Medium, severity.Low, alpha-bug

#138 fix: Edit FindCommand to display suitable message for no matches
  src/main/java/trackup/logic/Messages.java
  src/main/java/trackup/logic/commands/FindCommand.java
  src/test/java/trackup/logic/commands/FindCommandTest.java
Labels: priority.Medium, severity.Low, alpha-bug

#125 task: Improve test coverage for event related classes
  src/main/java/trackup/logic/commands/DeleteEventCommand.java
  src/main/java/trackup/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateEventAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBookWithEvents.json
  src/test/java/trackup/logic/commands/AddCommandTest.java
  src/test/java/trackup/logic/commands/AddEventCommandTest.java
  src/test/java/trackup/logic/commands/CommandTestUtil.java
  src/test/java/trackup/logic/commands/DeleteEventCommandTest.java
  src/test/java/trackup/logic/parser/AddEventCommandParserTest.java
  src/test/java/trackup/logic/parser/AddressBookParserTest.java
  src/test/java/trackup/logic/parser/DeleteEventCommandParserTest.java
  src/test/java/trackup/logic/parser/ParserUtilTest.java
  src/test/java/trackup/model/AddressBookTest.java
  src/test/java/trackup/model/ModelManagerTest.java
  src/test/java/trackup/model/event/EventTest.java
  src/test/java/trackup/storage/JsonAdaptedEventTest.java
  src/test/java/trackup/storage/JsonSerializableAddressBookTest.java
  src/test/java/trackup/testutil/EventBuilder.java
  src/test/java/trackup/testutil/EventUtil.java
  src/test/java/trackup/testutil/TypicalEvents.java
Labels: priority.High

#123 feat: Implement event listing by updating GUI
  src/main/java/trackup/model/ModelManager.java
  src/main/java/trackup/model/util/SampleDataUtil.java
  src/main/java/trackup/ui/EventCard.java
  src/main/java/trackup/ui/EventListPanel.java
  src/main/java/trackup/ui/MainWindow.java
  src/main/java/trackup/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#129 Improve code quality across core logic classes with defensive coding and assertion practices (closes #128)
  src/main/java/trackup/logic/parser/ArgumentTokenizer.java
  src/main/java/trackup/logic/parser/ParserUtil.java
  src/main/java/trackup/model/AddressBook.java
  src/main/java/trackup/model/event/UniqueEventList.java
  src/main/java/trackup/model/person/UniquePersonList.java
  src/test/java/trackup/logic/parser/ArgumentTokenizerTest.java
  src/test/java/trackup/logic/parser/ParserUtilTest.java
Labels: priority.Medium

#140 feat: Add notes attribute to persons
  docs/UserGuide.md
  src/main/java/trackup/logic/commands/AddNoteCommand.java
  src/main/java/trackup/logic/commands/DeleteNoteCommand.java
  src/main/java/trackup/logic/commands/EditCommand.java
  src/main/java/trackup/logic/parser/AddNoteCommandParser.java
  src/main/java/trackup/logic/parser/AddressBookParser.java
  src/main/java/trackup/logic/parser/DeleteNoteCommandParser.java
  src/main/java/trackup/model/note/Note.java
  src/main/java/trackup/model/person/Person.java
  src/main/java/trackup/storage/JsonAdaptedNote.java
  src/main/java/trackup/storage/JsonAdaptedPerson.java
  src/main/java/trackup/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBookWithEvents.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/trackup/logic/commands/AddNoteCommandTest.java
  src/test/java/trackup/logic/commands/DeleteNoteCommandTest.java
  src/test/java/trackup/logic/parser/AddNoteCommandParserTest.java
  src/test/java/trackup/logic/parser/AddressBookParserTest.java
  src/test/java/trackup/logic/parser/DeleteNoteCommandParserTest.java
  src/test/java/trackup/model/person/PersonTest.java
  src/test/java/trackup/storage/JsonAdaptedEventTest.java
  src/test/java/trackup/storage/JsonAdaptedPersonTest.java
  src/test/java/trackup/testutil/PersonBuilder.java
  src/test/java/trackup/testutil/TypicalPersons.java
Labels: priority.High

#120 fix(deleteby): improve error messages for no criteria and no match cases
  src/main/java/trackup/logic/Messages.java
  src/main/java/trackup/logic/commands/DeleteByCommand.java
Labels: priority.High, alpha-bug

#122 feat(add): provide specific error messages for missing required fields in add command
  src/main/java/trackup/logic/commands/DeleteByCommand.java
  src/main/java/trackup/logic/parser/AddCommandParser.java
  src/test/java/trackup/logic/commands/DeleteByCommandTest.java
  src/test/java/trackup/logic/parser/AddCommandParserTest.java
Labels: priority.Medium, alpha-bug

#152 docs: Add toggle command to userdoc
  docs/UserGuide.md
Labels: alpha-bug

#155 docs: Add sort command to UG
  docs/UserGuide.md
Labels: alpha-bug

#153 Bug: Add category parameter to DeleteByCommand
  src/main/java/trackup/logic/commands/DeleteByCommand.java
  src/main/java/trackup/logic/parser/DeleteByCommandParser.java
  src/test/java/trackup/logic/commands/DeleteByCommandTest.java
  src/test/java/trackup/logic/parser/AddressBookParserTest.java
  src/test/java/trackup/logic/parser/DeleteByCommandParserTest.java
Labels: alpha-bug

#148 Bug: Fix SortCommand parsing issues
  src/main/java/trackup/logic/parser/SortCommandParser.java
  src/test/java/trackup/logic/parser/SortCommandParserTest.java
Labels: alpha-bug

#141 fix: sortCommand allows empty description to display original list
  src/main/java/trackup/logic/commands/SortCommand.java
  src/main/java/trackup/logic/parser/SortCommandParser.java
  src/main/java/trackup/model/ModelManager.java
  src/test/java/trackup/logic/parser/SortCommandParserTest.java
Labels: alpha-bug

#159 docs: Update UG for v1.5
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/Ui1.png
  docs/index.md
  src/main/java/trackup/logic/commands/DeleteEventCommand.java
Labels: priority.High

#150 fix: Edit handlePreviousWeek and handleNextWeek to correctly create month year label
  src/main/java/trackup/ui/MainWindow.java
Labels: severity.Medium, alpha-bug

#160 fix: Edit AddCommand's message usage
  src/main/java/trackup/logic/commands/AddCommand.java
Labels: alpha-bug

#207 fix: Edit accelarator logic for week navigation shortcut to work properly
  src/main/java/trackup/ui/MainWindow.java
  src/main/java/trackup/ui/WeeklyCalendarView.java
Labels: type.Bug, severity.High

#208 fix: Edit MainWindow.fxml to set sizes for panes with events and contacts
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Low

#209 fix: Add larger padding for category label
  src/main/java/trackup/ui/PersonCard.java
Labels: type.Bug, severity.Low

#210 fix: Edit tag label to have max width and wrapping enabled
  src/main/java/trackup/ui/PersonCard.java
Labels: type.Bug, severity.Low

#211 Fix DG AddCommand sequence diagram: removed irrelevant Bob and Alice lifelines
  docs/images/AddCommandSequenceDiagram.png
Labels: type.Bug, severity.VeryLow, alpha-bug

#212 Fix clear command message to reflect product name 'TrackUp'
  src/main/java/trackup/logic/commands/ClearCommand.java
Labels: type.Bug, severity.VeryLow

#213 Fix UG: Remove invalid sort command example with multiple fields
  docs/UserGuide.md
Labels: type.Bug, severity.Low

#215 Disallow numeric-only names in AddCommand (cherry-pick)
  src/main/java/trackup/model/person/Name.java
  src/test/java/trackup/model/person/NameTest.java
Labels: type.Bug, severity.Medium

#216 Fix email validation to reject invalid domain formats
  src/main/java/trackup/model/person/Email.java
  src/test/java/trackup/model/person/EmailTest.java
Labels: type.Bug, severity.Medium

#222 Fix: DeleteByCommand issues found in PE-D
  src/main/java/trackup/logic/commands/DeleteByCommand.java
  src/main/java/trackup/model/person/Email.java
Labels: type.Bug, severity.Medium, alpha-bug

#221 Fix DG: Add manual testing instructions for Saving Data section
  docs/DeveloperGuide.md
Labels: type.Bug, severity.Low

#227 refactor: Rename user facing instances of addressbook to trackup
  src/main/java/trackup/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/trackup/storage/JsonUserPrefsStorageTest.java
Labels: type.Enhancement, severity.Medium

#223 Fix: AddNoteCommand issues found in PE-D
  src/main/java/trackup/logic/commands/AddNoteCommand.java
  src/main/java/trackup/model/note/Note.java
  src/test/java/trackup/logic/commands/AddNoteCommandTest.java
Labels: type.Bug, severity.Medium

#225 docs: Update User Guide for final submission
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addEvent.png
  docs/images/addNote.png
  docs/images/findAlexDavid.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/searchDoe.png
  docs/images/sortByNameAscending.png
  docs/images/sortByNameDescending.png
  docs/images/toggleDateTime.png
  docs/images/togglePhone.png
  src/main/java/trackup/logic/commands/ClearCommand.java
Labels: priority.High

#229 docs: Update Developer Guide for final submission
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/trackup/logic/commands/DeleteByCommand.java
  src/main/java/trackup/logic/parser/SortCommandParser.java
  src/test/java/trackup/logic/commands/DeleteByCommandTest.java
Labels: priority.High
